export const SAVE_USER_INFO_ERROR = 'SAVE_USER_INFO_ERROR';//保存用户信息失败
// 保存用户信息
export const SAVE_USER_INFO = 'SAVE_USER_INFO';
export const SAVE_USER_INFO_ASYNC = 'SAVE_USER_INFO_ASYNC';

// 保存用户信息 通过doctorId
export const SAVE_USER_INFO_BY_DOCTORID = 'SAVE_USER_INFO_BY_DOCTORID';
export const SAVE_USER_INFO_BY_DOCTORID_ASYNC = 'SAVE_USER_INFO_BY_DOCTORID_ASYNC';

// 获取菜单路由
export const SAVE_ROUTERS = 'SAVE_ROUTERS';
export const SAVE_ROUTERS_ASYNC = 'SAVE_ROUTERS_ASYNC';